Repository Sulagna-Dutta-Roy/Covid19-website, pull requests merged in 2022-08, with the labels that each got.

#50 Readme update
  README.md
Labels: enhancement, HSOC22-Level-1, HSOC22

#51 Readme update
  protect.html
Labels: enhancement, HSOC22-Level-3, HSOC22

#52 Modified appearance of Wash-hands.html, Wear_mask.html and Get_vaccin…
  Get_vaccinated.html
  Wash_hands.html
  Wear_mask.html
  details.html
  index.html
Labels: enhancement, HSOC22-Level-2, HSOC22
