Repository Sulagna-Dutta-Roy/Covid19-website, pull requests merged in 2022-07, with the labels that each got.

#12 changed documentation
  index.html
Labels: documentation, enhancement, Hsoc Level2

#15 Info added to symptoms and causes
  Images/s2.jpeg
  Images/s3.jpeg
  Images/s4.jpeg
  Images/sympbg.png
  causes.html
  index.html
Labels: enhancement, Hsoc Level2

#17 Fix: Improved accessibility
  index.html
  style.css
Labels: enhancement, HSOC22-Level-3

#22 improvement in protect.html
  causes.html
  protect.html
Labels: enhancement, HSOC22-Level-2, HSOC22

#23 Enhance the precautions section
  index.html
Labels: enhancement, HSOC22-Level-2, HSOC22

#30 Fix: Linked footer navbar links to matching sections
  index.html
Labels: enhancement, HSOC22-Level-2, HSOC22

#31 Working-Dark_Mode
  Images/background.svg
  Images/moon.svg
  Images/sun.svg
  index.html
  style.css
Labels: enhancement, HSOC22-Level-3, HSOC22

#33 Fixed the issue with toggle mode icon #32 and background img of causes.html
  causes.html
  index.html
Labels: bug, enhancement, HSOC22-Level-2, HSOC22

#37 designed the footer a bit
  index.html
Labels: enhancement, HSOC22-Level-2, HSOC22

#41 Fix issue #35 Added required pages
  Get_vaccinated.html
  Wash_hands.html
  Wear_mask.html
  index.html
Labels: enhancement, HSOC22-Level-3, HSOC22

#42 Added login page
  index.html
  login.html
  style.css
Labels: enhancement, HSOC22-Level-2, HSOC22

#43 Added a Covid Statistics Counter
  index.html
  index.js
  style.css
Labels: enhancement, HSOC22-Level-2, HSOC22

#44 Responsive protection and causes page
  causes.html
  protect.html
Labels: enhancement, HSOC22-Level-1, HSOC22
